### ISSUE TITLE
Recherche par line-ups partiellement déficiente

### ISSUE THREAD

**Issue by Dioneeo** [xian310/gutsofdarkness#11]
Lorsqu'on entre un nom d'artiste dans la barre de recherche avec l'option "line-ups", les dix premiers résultats apparaissent bien et l'on aboutit sur la page du disque concerné en cliquant sur l'un ou l'autre de ces liens. Mais en cliquant sur "voir tous les résultats" on arrive sur une page vide (noire). Comme avec les clics sur le lien "correction orthographiques" des chroniques, cette page ne propose pas non-plus l'onglet "menu principal" habituellement disponible sur la gauche de l'écran.

**Comment by xian310** [comment]
Corrigé
