### ISSUE TITLE
Edit "amalagamant" dans les forums

### ISSUE THREAD

**Issue by Dioneeo** [xian310/gutsofdarkness#12]
Dans les forums publics - même souci qu'avec les MP (cf ce bug) - l'edit d'un post aboutit à une publication après correction où tout le texte est "amalgamé", c'est à dire d'un bloc sans les sauts de lignes et espaces. Ceci-dit on peut rajouter ces espaces et sauts en corrigeant une seconde fois (contrairement à ce qui arrive avec les MP, chaque nouvelle réponse y apparaissant "amalgamée" aux messages précédents même si on réinsère les espaces/sauts avant d'envoyer la réponse).

**Comment by NumeroSixGOD** [comment]
Pas seulement dans les forums. Dans les tracklists également quand ils sont créés post-bascule.
