### ISSUE TITLE
tracklist ne peut plus être affiché après création ou édition

### ISSUE THREAD

**Issue by Rastig** [xian310/gutsofdarkness#17]
Quand on ajoute, ou crée ou modifie une tracklist, le retour à la ligne ne fonctionne plus (pas testé avec un autre caractère que le pipe).

Ce qui donne un affichage buggé, tout sur une ligne, avec plein de caractères qui ne peuvent être affichés, voir : chronique Blue Öyster Cult › On Your Feet or on Your Knees
 
 https://www.gutsofdarkness.com/god/objet.php?objet=1971

**Comment by xian310** [comment]
Une des lignes de la validation de saisie foutait la grouille.
