### ISSUE TITLE
Fonction jukebox indispo

### ISSUE THREAD

**Issue by Dioneeo** [xian310/gutsofdarkness#31]
Une lectrice nous signale sur la boîte de la page FB que la fonction jukebox ne fonctionne pas... (J'avoue que j'en avais même oublié l'existence). Je lui ai répondu qu'on était en cour de débuggage depuis migration. (Bon, je dis pas, c'est pas le truc le plus urgent mais je transmets).

**Comment by xian310** [comment]
Ce module est désormais supprimé du site.
