### ISSUE TITLE
Vous écoutez quoi là ?

### ISSUE THREAD

**Issue by ctritten** [xian310/gutsofdarkness#43]
Si un commentaire est spécifié :
- [x] ajout du commentaire dans le topic "vous écoutez quoi là ?"
- [x] ajout du commentaire dans les commentaires de l'objet.
- [x] ajout de l'objet dans les 20 derniers objets écoutés par l'utilisateur.

Si aucun commentaire n'est spécifié :
- [x] ajout de l'objet dans les 20 derniers objets écoutés par l'utilisateur.

Ajout de pages de consultation des écoutes :
- [x] les 20 dernières écoutes d'un membre (section membre)
- les dernières écoutes tous disques confondus
- [x] les dernières écoutes d'un disque
- les disques les plus écoutés

Divers :
- [x] Mettre plus en avant le fait qu'on peut signaler qu'on écoute un disque.
- [x] Empêcher la soumission de plusieurs écoutes par un même membre sur une même plage horaire.

**Comment by xian310** [comment]
Lors de l'ajout du commentaire sur la page du disque, ne pas mettre le titre de l'album ni la pochette.
