### ISSUE TITLE
Caractères spéciaux remplacés par ?

### ISSUE THREAD

**Issue by NumeroSixGOD** [xian310/gutsofdarkness#7]
Les caractères spéciaux correspondant au moins aux lettres turques ne passent plus dans les line-up, chroniques, recommandations etc... (je pense partout en fait, y compris tracklist et artistes, mais j'en ai pas créée de nouveaux du coup). Elles sont remplacées par un ?.

**Comment by NumeroSixGOD** [comment]
Je confirme que ce sont bien tous les caractères spéciaux, j'ai testé avec le japonais c'est pareil. Et c'est refusé partout, titre, titre des morceaux, line-up, enregistrement etc.

**Comment by xian310** [comment]
Corrigé ;)
