### ISSUE TITLE
Chro Anadolu Pop disparu, à remettre en ligne 

### ISSUE THREAD

**Issue by NumeroSixGOD** [xian310/gutsofdarkness#82]
https://www.gutsofdarkness.com/god/objet.php?objet=18641

Merci d'utiliser l'outil "modifier le chro", ou l'outil de correction, pour ne pas modifier la date de mise en ligne (comme c'était ma première chro du genre y avait une logique).

**Comment by xian310** [comment]
Chronique rétablie.
