### ISSUE TITLE
Corrections ortographiques indisponibles

### ISSUE THREAD

**Issue by Dioneeo** [xian310/gutsofdarkness#9]
Accès aux corrections orthographiques des chroniques indisponible. Cliquer sur le lien "corriger l'orthographe" renvoie sur une page vide/noire/inactive (avec l'index latéral "menu principal" indisponible, également).

**Comment by Dioneeo** [comment]
Le lien d'accès depuis le forum interne aux corrections orthographiques "proposées" renvoie également sur une page vide/noire/inactive.

**Comment by xian310** [comment]
Corrigé
